import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(18, GPIO.OUT)
print ('Green LED on')
GPIO.output(18, GPIO.HIGH)
time.sleep(5)
print ('Green LED off')
GPIO.output(18, GPIO.LOW)
GPIO.setup(16, GPIO.OUT)
print ('Yellow LED on')
GPIO.output(18, GPIO.HIGH)
GPIO.output(16, GPIO.HIGH)
time.sleep(1)
print ('Yellow LED off')
GPIO.output(18, GPIO.LOW)
GPIO.output(16, GPIO.LOW)
print ('Red LED on')
GPIO.output(16, GPIO.HIGH)
time.sleep(4)
print ('Red LED off')
GPIO.output(16, GPIO.LOW)
